terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = { source = "hashicorp/aws" version = "~> 6.0" }
  }
}

provider "aws" { region = var.aws_region }

resource "aws_connect_instance" "acme_support" {
  instance_alias                   = "acme-support"
  identity_management_type         = "CONNECT_MANAGED"
  inbound_calls_enabled             = true
  outbound_calls_enabled            = true
  contact_flow_logs_enabled         = false
  contact_lens_enabled              = true
  auto_resolve_best_voices_enabled  = true
  early_media_enabled               = true
  multi_party_conference_enabled    = false
  tags = {
    "Environment" = "dev"
    "ManagedBy" = "Terraform"
  }
}

resource "aws_connect_hours_of_operation" "always_open" {
  instance_id = aws_connect_instance.acme_support.id
  name        = "Generated 24x7"
  description = "24x7 hours generated by AWS Connect Migration Accelerator Tool"
  time_zone   = "UTC"
  config {
    day = "MONDAY"
    start_time {
      hours   = 0
      minutes = 0
    }
    end_time {
      hours   = 23
      minutes = 59
    }
  }
  config {
    day = "TUESDAY"
    start_time {
      hours   = 0
      minutes = 0
    }
    end_time {
      hours   = 23
      minutes = 59
    }
  }
  config {
    day = "WEDNESDAY"
    start_time {
      hours   = 0
      minutes = 0
    }
    end_time {
      hours   = 23
      minutes = 59
    }
  }
  config {
    day = "THURSDAY"
    start_time {
      hours   = 0
      minutes = 0
    }
    end_time {
      hours   = 23
      minutes = 59
    }
  }
  config {
    day = "FRIDAY"
    start_time {
      hours   = 0
      minutes = 0
    }
    end_time {
      hours   = 23
      minutes = 59
    }
  }
  config {
    day = "SATURDAY"
    start_time {
      hours   = 0
      minutes = 0
    }
    end_time {
      hours   = 23
      minutes = 59
    }
  }
  config {
    day = "SUNDAY"
    start_time {
      hours   = 0
      minutes = 0
    }
    end_time {
      hours   = 23
      minutes = 59
    }
  }
}

resource "aws_connect_security_profile" "generated_agent" {
  instance_id = aws_connect_instance.acme_support.id
  name        = "AWS Connect Migration Accelerator Agent"
  description = "Least-privilege profile for generated agents"
  permissions = ["BasicAgentAccess", "OutboundCallAccess"]
}

resource "aws_connect_queue" "english" {
  instance_id           = aws_connect_instance.acme_support.id
  name                  = "English"
  description           = "Generated routing skill"
  hours_of_operation_id = aws_connect_hours_of_operation.always_open.hours_of_operation_id
}

resource "aws_connect_routing_profile" "english" {
  instance_id               = aws_connect_instance.acme_support.id
  name                      = "English routing"
  description               = "Generated routing skill"
  default_outbound_queue_id = aws_connect_queue.english.queue_id
  media_concurrencies {
    channel     = "VOICE"
    concurrency = 1
  }
  queue_configs {
    channel  = "VOICE"
    delay    = 0
    priority = 1
    queue_id = aws_connect_queue.english.queue_id
  }
}

resource "aws_connect_user" "alice" {
  instance_id        = aws_connect_instance.acme_support.id
  name               = "Alice"
  password = var.agent_passwords["Alice"]
  routing_profile_id = aws_connect_routing_profile.english.routing_profile_id
  security_profile_ids = [aws_connect_security_profile.generated_agent.security_profile_id]
  identity_info {
    first_name = "James"
    last_name  = "Son"
  }
  phone_config {
    phone_type                    = "SOFT_PHONE"
    auto_accept                   = false
    after_contact_work_time_limit = 60
  }
}
