from __future__ import annotations

import json
import re
import uuid
from io import BytesIO
from zipfile import ZIP_DEFLATED, ZipFile

from .models import ConnectInstanceSpec, ContactFlowSpec


def _hcl_string(value: str) -> str:
    # HCL quoted strings still interpolate these sequences unless escaped.
    return json.dumps(value.replace("${", "$${").replace("%{", "%%{"))


def _resource_name(value: str) -> str:
    name = re.sub(r"[^a-zA-Z0-9_]", "_", value).strip("_") or "resource"
    if name[0].isdigit():
        name = f"connect_{name}"
    return name.lower()


def _tags(tags: dict[str, str]) -> str:
    values = tags or {"ManagedBy": "Terraform"}
    return "\n".join(
        f"    {_hcl_string(key)} = {_hcl_string(value)}" for key, value in sorted(values.items())
    )


def _hours_resource(spec: ConnectInstanceSpec, instance_ref: str) -> str:
    configs = []
    for day in ("MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"):
        configs.append(f'''  config {{
    day = "{day}"
    start_time {{
      hours   = 0
      minutes = 0
    }}
    end_time {{
      hours   = 23
      minutes = 59
    }}
  }}''')
    return f'''resource "aws_connect_hours_of_operation" "always_open" {{
  instance_id = {instance_ref}.id
  name        = "Generated 24x7"
  description = "24x7 hours generated by AWS Connect Migration Accelerator Tool"
  time_zone   = {_hcl_string(spec.time_zone)}
{chr(10).join(configs)}
}}
'''


def _flow_content(name: str, message: str) -> str:
    start = str(uuid.uuid5(uuid.NAMESPACE_URL, f"connectcraft:{name}:message"))
    finish = str(uuid.uuid5(uuid.NAMESPACE_URL, f"connectcraft:{name}:disconnect"))
    content = {
        "Version": "2019-10-30",
        "StartAction": start,
        "Actions": [
            {
                "Identifier": start,
                "Type": "MessageParticipant",
                "Transitions": {"NextAction": finish, "Errors": [], "Conditions": []},
                "Parameters": {"Text": message},
            },
            {
                "Identifier": finish,
                "Type": "DisconnectParticipant",
                "Transitions": {},
                "Parameters": {},
            },
        ],
    }
    # Terraform jsonencode accepts a JSON-compatible object literal.
    return json.dumps(content, indent=2).replace("${", "$${").replace("%{", "%%{")


def _reject_resource_name_collisions(spec: ConnectInstanceSpec) -> None:
    groups = {
        "skills": [item.name for item in spec.skills],
        "agents": [item.username for item in spec.agents],
        "contact flows": [item.name for item in spec.contact_flows],
        "DNIS entries": [item.name for item in spec.dnis],
    }
    for label, names in groups.items():
        normalized = [_resource_name(name) for name in names]
        if len(set(normalized)) != len(normalized):
            raise ValueError(f"{label} contain names that collide after Terraform normalization")


def render_files(spec: ConnectInstanceSpec) -> dict[str, str]:
    _reject_resource_name_collisions(spec)
    instance_name = _resource_name(spec.instance_alias)
    instance_ref = f"aws_connect_instance.{instance_name}"
    directory = ""
    if spec.directory_id:
        directory = f"  directory_id             = {_hcl_string(spec.directory_id)}\n"

    sections = [f'''terraform {{
  required_version = ">= 1.5.0"
  required_providers {{
    aws = {{ source = "hashicorp/aws" version = "~> 6.0" }}
  }}
}}

provider "aws" {{ region = var.aws_region }}

resource "aws_connect_instance" "{instance_name}" {{
  instance_alias                   = {_hcl_string(spec.instance_alias)}
  identity_management_type         = {_hcl_string(spec.identity_management_type)}
{directory}  inbound_calls_enabled             = {str(spec.inbound_calls_enabled).lower()}
  outbound_calls_enabled            = {str(spec.outbound_calls_enabled).lower()}
  contact_flow_logs_enabled         = {str(spec.contact_flow_logs_enabled).lower()}
  contact_lens_enabled              = {str(spec.contact_lens_enabled).lower()}
  auto_resolve_best_voices_enabled  = {str(spec.auto_resolve_best_voices_enabled).lower()}
  early_media_enabled               = {str(spec.early_media_enabled).lower()}
  multi_party_conference_enabled    = {str(spec.multi_party_conference_enabled).lower()}
  tags = {{
{_tags(spec.tags)}
  }}
}}
''']

    if spec.skills:
        sections.append(_hours_resource(spec, instance_ref))
        sections.append(f'''resource "aws_connect_security_profile" "generated_agent" {{
  instance_id = {instance_ref}.id
  name        = "AWS Connect Migration Accelerator Agent"
  description = "Least-privilege profile for generated agents"
  permissions = ["BasicAgentAccess", "OutboundCallAccess"]
}}
''')

    for skill in spec.skills:
        key = _resource_name(skill.name)
        sections.append(f'''resource "aws_connect_queue" "{key}" {{
  instance_id           = {instance_ref}.id
  name                  = {_hcl_string(skill.name)}
  description           = {_hcl_string(skill.description)}
  hours_of_operation_id = aws_connect_hours_of_operation.always_open.hours_of_operation_id
}}

resource "aws_connect_routing_profile" "{key}" {{
  instance_id               = {instance_ref}.id
  name                      = {_hcl_string(skill.name + " routing")}
  description               = {_hcl_string(skill.description)}
  default_outbound_queue_id = aws_connect_queue.{key}.queue_id
  media_concurrencies {{
    channel     = {_hcl_string(skill.channel)}
    concurrency = {skill.concurrency}
  }}
  queue_configs {{
    channel  = {_hcl_string(skill.channel)}
    delay    = {skill.delay_seconds}
    priority = {skill.priority}
    queue_id = aws_connect_queue.{key}.queue_id
  }}
}}
''')

    for agent in spec.agents:
        key = _resource_name(agent.username)
        skill_key = _resource_name(agent.skill_name)
        password = ""
        if spec.identity_management_type == "CONNECT_MANAGED":
            password = f'  password = var.agent_passwords[{_hcl_string(agent.username)}]\n'
        email = ""
        if agent.email and spec.identity_management_type != "SAML":
            email = f"    email      = {_hcl_string(agent.email)}\n"
        desk_phone = ""
        if agent.desk_phone_number:
            desk_phone = f"    desk_phone_number = {_hcl_string(agent.desk_phone_number)}\n"
        sections.append(f'''resource "aws_connect_user" "{key}" {{
  instance_id        = {instance_ref}.id
  name               = {_hcl_string(agent.username)}
{password}  routing_profile_id = aws_connect_routing_profile.{skill_key}.routing_profile_id
  security_profile_ids = [aws_connect_security_profile.generated_agent.security_profile_id]
  identity_info {{
    first_name = {_hcl_string(agent.first_name)}
    last_name  = {_hcl_string(agent.last_name)}
{email}  }}
  phone_config {{
    phone_type                    = {_hcl_string(agent.phone_type)}
{desk_phone}    auto_accept                   = {str(agent.auto_accept).lower()}
    after_contact_work_time_limit = {agent.after_contact_work_seconds}
  }}
}}
''')

    for flow in spec.contact_flows:
        key = _resource_name(flow.name)
        sections.append(f'''resource "aws_connect_contact_flow" "{key}" {{
  instance_id = {instance_ref}.id
  name        = {_hcl_string(flow.name)}
  description = {_hcl_string(flow.description)}
  type        = {_hcl_string(flow.type)}
  content = <<-JSON
{_flow_content(flow.name, flow.welcome_message)}
JSON
}}
''')

    for dnis in spec.dnis:
        key = _resource_name(dnis.name)
        flow_key = _resource_name(dnis.contact_flow_name)
        prefix = f"  prefix       = {_hcl_string(dnis.prefix)}\n" if dnis.prefix else ""
        sections.append(f'''resource "aws_connect_phone_number" "{key}" {{
  target_arn   = {instance_ref}.arn
  country_code = {_hcl_string(dnis.country_code)}
  type         = {_hcl_string(dnis.number_type)}
{prefix}  description  = {_hcl_string("DNIS " + dnis.name)}
}}

resource "aws_connect_phone_number_contact_flow_association" "{key}" {{
  phone_number_id = aws_connect_phone_number.{key}.id
  instance_id     = {instance_ref}.id
  contact_flow_id = aws_connect_contact_flow.{flow_key}.contact_flow_id
}}
''')

    variables = f'''variable "aws_region" {{
  description = "AWS region for Amazon Connect"
  type        = string
  default     = {_hcl_string(spec.region)}
}}
'''
    tfvars = "# Never commit this file. Supply values through your approved secret store.\n"
    if spec.identity_management_type == "CONNECT_MANAGED" and spec.agents:
        variables += '''
variable "agent_passwords" {
  description = "Initial passwords for Connect-managed agent users"
  type        = map(string)
  sensitive   = true
}
'''
        tfvars += "agent_passwords = {\n" + "\n".join(
            f'  {_hcl_string(agent.username)} = "REPLACE_USING_SECRET_INJECTION"'
            for agent in spec.agents
        ) + "\n}\n"

    outputs = f'''output "connect_instance_id" {{ value = {instance_ref}.id }}
output "connect_instance_arn" {{ value = {instance_ref}.arn }}

output "claimed_dnis_numbers" {{
  value = {{
{chr(10).join(f'    {_hcl_string(item.name)} = aws_connect_phone_number.{_resource_name(item.name)}.phone_number' for item in spec.dnis)}
  }}
}}
'''
    files = {
        "main.tf": "\n".join(sections),
        "variables.tf": variables,
        "outputs.tf": outputs,
    }
    if spec.identity_management_type == "CONNECT_MANAGED" and spec.agents:
        files["terraform.tfvars.example"] = tfvars
    return files


def render_existing_dnis_contact_flow_files(
    *,
    region: str,
    instance_id: str,
    phone_number_id: str,
    flow: ContactFlowSpec,
) -> dict[str, str]:
    """Render a focused package that attaches a new flow to an existing DNIS."""
    flow_key = _resource_name(flow.name)
    main = f'''terraform {{
  required_version = ">= 1.5.0"
  required_providers {{
    aws = {{ source = "hashicorp/aws" version = "~> 6.0" }}
  }}
}}

provider "aws" {{ region = var.aws_region }}

resource "aws_connect_contact_flow" "{flow_key}" {{
  instance_id = var.connect_instance_id
  name        = {_hcl_string(flow.name)}
  description = {_hcl_string(flow.description)}
  type        = {_hcl_string(flow.type)}
  content = <<-JSON
{_flow_content(flow.name, flow.welcome_message)}
JSON
}}

resource "aws_connect_phone_number_contact_flow_association" "{flow_key}" {{
  phone_number_id = var.existing_dnis_phone_number_id
  instance_id     = var.connect_instance_id
  contact_flow_id = aws_connect_contact_flow.{flow_key}.contact_flow_id
}}
'''
    variables = f'''variable "aws_region" {{
  description = "AWS region containing the existing Amazon Connect instance"
  type        = string
  default     = {_hcl_string(region)}
}}

variable "connect_instance_id" {{
  description = "ID of the existing Amazon Connect instance"
  type        = string
  default     = {_hcl_string(instance_id)}
}}

variable "existing_dnis_phone_number_id" {{
  description = "Amazon Connect phone-number ID for the existing DNIS"
  type        = string
  default     = {_hcl_string(phone_number_id)}
}}
'''
    outputs = f'''output "contact_flow_id" {{
  value = aws_connect_contact_flow.{flow_key}.contact_flow_id
}}

output "existing_dnis_phone_number_id" {{
  value = var.existing_dnis_phone_number_id
}}
'''
    return {
        "main.tf": main,
        "variables.tf": variables,
        "outputs.tf": outputs,
    }


def files_to_zip(files: dict[str, str]) -> bytes:
    buffer = BytesIO()
    with ZipFile(buffer, "w", ZIP_DEFLATED) as archive:
        for filename, content in files.items():
            archive.writestr(filename, content)
    return buffer.getvalue()
